### PR TITLE
add "packaging_format" key to manifest.json

### PR DESCRIPTION
**Pull request by Psycojoker**
Following the decision taken during last meeting.

See "## Format version (packaging_version)" here http://pv.yunohost.org/meeting/63-yunohost-3-2016/

### CODE REVIEW

**Comment by mbugeia** [comment]
Hi, thanks but it kind of bother me to add something that is neither implemented or documented... What do you think ?

**Comment by Psycojoker** [comment]
Hey,

In this case I find that acceptable since this repository is an official application and we want to do that to move forward for 2.4 but I can understand your hesitations. Implementation and doc are coming.

**Comment by mbugeia** [comment]
Ok, I will merge because I don't want to block anything but I don't understand the purpose of this parameter.

**Comment by Psycojoker** [comment]
Oh, that was the missing information, sorry :/

The idea is to introduce a "package format version number" so we can modify how app are packages while keeping a bit of retrocompatibility if needed, document how to upgrade and refuse to install to old not upgraded apps.

**Comment by mbugeia** [comment]
Wouldn't it be simpler/clearer to add a minimum yunohost version to the manifest like discussed here https://dev.yunohost.org/issues/113 ? Or maybe I still don't really understand how it is supposed to work.

**Comment by Psycojoker** [comment]
The "bind apps to yunohost version" is the firefox approach where all your plugins breaks at every upgrade, we don't want that for our users apps. This approach is more like the chrome one: decoralation between yunohost version and package version, this way, as long as we keep things in the same way in YunoHost apps won't break with a new version and if we need to change that we will be able to do easy to follow documentation for that. This will reduce the cost of doing a release for YunoHost.

**Pull request merged**
